name: com421

services:
    base:
        build: .
        image: com421/washington-sustainable-project
        ports: 
            - "80:80"
#            - "127.0.0.1:80:80"
        volumes:
            - ./:/usr/src/app
